baseurl = "https://cmontella.gitlab.io/hivemindwebsite/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Hive Mind OS"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "An OS For Robots"
  logo = ""
  favicon = ""
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Corey Montella"
  email = "youremail@domain.com"
  gitlab = "cmontella"


[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Documentation"
    url = "page/docs/"
    weight = 4

[[menu.main]]
    name = "Community"
    url = "page/community/"
    weight = 5

[[menu.main]]
    name = "Download"
    url = "page/docs/"
    weight = 6

